### PR TITLE
Fix `Scss#sass_dir_relative_to_site_source` logic

### LINKED ISSUE #98: Jekyll scss converter fails if parent folder name contains brackets
I do not know if I just found a bug or a feature, but here's the issue:

If you have a Jekyll project in a folder `website` which is below another folder containing brackets, e.g. `/<somepath>/[my]websites/website`, Jekyll's scss converter cannot seem to find referenced files to import. For example here's the error message I get:

`Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    File to import not found or unreadable: imports/functions. on line 19`

If I rename the parent folder to something without brackets, it works again.

Note that I am talking about the *parent* folder of the project, not the name of the project folder itself. So I don't know why Jekyll or the conversion script would even care about this, but maybe it takes the whole path into account and then stumbles on the brackets (though I did not know of any rule that you cannot have brackets in path names).

### PR DESCRIPTION
**Pull request by ashmaroli**
Even though the method is named `sass_dir_relative_to_site_source`, the returned result is a path with `site.source` included.
Furthermore, since `site.source` is an absolute path, the returned path is absolute path as well.

This pull request proposes to strip away the `site.source` prefixed  after sanitization of the `sass_dir` attribute.

Additionally resolves #98

### CODE REVIEW

**Comment by DirtyF** [comment]
On an unrelated not, xenial comes with 2.5.3 by default, we could go bionic for this repo, to speed up tests: https://docs.travis-ci.com/user/reference/bionic/#ruby-support

**Comment by ashmaroli** [comment]
> we could go bionic for this repo, to speed up tests: https://docs.travis-ci.com/user/reference/bionic/#ruby-support

@DirtyF Please open a new ticket to handle this separately.
Thanks.

**Comment by ashmaroli** [comment]
We can't merge this right away since this changes the result of a public method. So let us wait for a comment from @parkr or @mattr-

**Comment by ashmaroli** [comment]
@jekyllbot: merge +minor

**Pull request merged**
