### PR TITLE
Allow including source line-no with `debug` option

### PR DESCRIPTION
**Pull request by ashmaroli**
ref: [#12 comment](https://github.com/jekyll/jekyll-sass-converter/issues/12#issuecomment-68542994)

Perhaps not something what everyone wants.. but IMO, its nevertheless better to have something till we support sourcemaps

### CODE REVIEW

**Comment by DirtyF** [comment]
@ashmaroli I'd rather support source maps, also do you know if this works with Sassc?

**Comment by ashmaroli** [comment]
> I'd rather support source maps, also do you know if this works with Sassc?

@DirtyF This is just implementing @jglovier's [comment from 2015](https://github.com/jekyll/jekyll-sass-converter/issues/12#issuecomment-68542994) and @parkr's consequent reaction.
Fast-forwards 4 years, I doubt they'd be interested in this anymore. Nevertheless, I've updated the branch to work with SassC.

**Comment by DirtyF** [comment]
See also #85

**Comment by ashmaroli** [comment]
Not sure if this is still valid with `sassc-ruby`...

**Comment by DirtyF** [comment]
@ashmaroli should we close this?

**Comment by ashmaroli** [comment]
Yeah, we have source-maps now.. That should be sufficient.

**Pull request closed without merging**
