### PR TITLE
Reduce overall class size

### PR DESCRIPTION
**Pull request by ntkme**
See https://github.com/jekyll/jekyll-sass-converter/pull/131#issuecomment-1049859420

### CODE REVIEW

**Comment by ashmaroli** [comment]
Thanks @ntkme
Lines `144-147` could be compacted as well.

**Comment by ntkme** [comment]
@ashmaroli I think these are all I can find.

**Review by ashmaroli — APPROVED** [review]
LGTM! :+1:

**Comment by ashmaroli** [comment]
Thanks @ntkme
@jekyllbot: merge +dev

**Comment by ashmaroli** [comment]
@jekyllbot: merge +dev

**Pull request merged**
